version: '3'
services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mysql-pw

